# Generated by Django 3.2.10 on 2022-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=50)),
                ('arid_no', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
