# Generated by Django 3.2.10 on 2022-05-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Authorized',
        ),
    ]
