# Generated by Django 3.2.10 on 2022-05-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0003_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
